export const glasses = [
  { value: 'brandy', label: 'Brandy' },
  { value: 'champagneFlute', label: 'Champagne Flute' },
  { value: 'collins', label: 'Collins' },
  { value: 'copperMug', label: 'Copper Mug' },
  { value: 'cordial', label: 'Cordial' },
  { value: 'coupe', label: 'Coupe' },
  { value: 'highball', label: 'Highball' },
  { value: 'hurricane', label: 'Hurricane' },
  { value: 'irishCoffee', label: 'Irish Coffee' },
  { value: 'margarita', label: 'Margarita' },
  { value: 'martini', label: 'Martini Glass' },
  { value: 'nickAndNora', label: 'Nick and Nora' },
  { value: 'rocks', label: 'Rocks Glass' },
  { value: 'shot', label: 'Shot Glass' },
  { value: 'wine', label: 'Wine Glass' },
];

export const units = [
  { value: '', label: 'none' },
  { value: 'barspoon', label: 'barspoon' },
  { value: 'centiliters', label: 'cl' },
  { value: 'cup', label: 'cup' },
  { value: 'dash', label: 'dash' },
  { value: 'jigger', label: 'jigger' },
  { value: 'ounce', label: 'oz' },
  { value: 'part', label: 'part' },
  { value: 'pony', label: 'pony' },
  { value: 'splash', label: 'splash' },
  { value: 'tablespoon', label: 'tbsp' },
  { value: 'teaspoon', label: 'tsp' },
];
